[package]
name = "Sliding-Puzzles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"

[profile.dev]
lto = "fat"
codegen-units = 1
opt-level = 3
